# Generated by Django 4.2.18 on 2025-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': [('can_add_recipe', 'Can add recipes'), ('can_edit_recipe', 'Can edit recipes')]},
        ),
    ]
