# Generated by Django 4.2.18 on 2025-02-06 17:22

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
