# Generated by Django 4.2.18 on 2025-02-18 12:01

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(validators=[recipe.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(validators=[recipe.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(validators=[recipe.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
