# Generated by Django 4.2.18 on 2025-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
