# Generated by Django 4.2.18 on 2025-02-14 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='featured_image',
            new_name='about_image',
        ),
    ]
